title: "Economic Stress and Psychological Well-being in Latin Americ"
description: "Longitudinal dataset (2000-2025) examining the relationship between economic stress indicators and mental health outcomes across 19 Latin American cou"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/economic-stress-and-psychological-well-being-in-latin-america-2000-2025"
